#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

./node_modules/.bin/concurrently \
    --kill-others-on-fail \
    --names "typecheck,format,lint" \
    "npm run typecheck" \
    "npm run lint --silent" \
    "npm run format" \