name: Learning workflows
on: pull_request
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: echo "cat .nvmrc"
      - run: npm install -g bats
      - run: bats -v
